package com.neonstrike.game;
import android.app.*;import android.os.*;import android.webkit.*;import android.widget.*;import android.view.*;import android.net.Uri;
public class MainActivity extends Activity {
 WebView web;String server="";
 public void onCreate(Bundle state){super.onCreate(state);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);web=new WebView(this);setContentView(web);enterFullscreen();web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setMediaPlaybackRequiresUserGesture(false);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setUserAgentString(web.getSettings().getUserAgentString()+" NeonStrikeAndroid");web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){if("about:blank".equals(r.getUrl().toString())){finish();return true;}return !sameServer(r.getUrl());}public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame())new AlertDialog.Builder(MainActivity.this).setTitle("서버 연결 실패").setMessage("PC에서 NeonStrike.exe를 실행하고 서버 주소와 네트워크 연결을 확인하세요.").setPositiveButton("다시 연결",(d,w)->web.loadUrl(server)).setNegativeButton("주소 변경",(d,w)->connect()).show();}});connect();}
 boolean sameServer(Uri u){Uri s=Uri.parse(server);return ("http".equals(u.getScheme())||"https".equals(u.getScheme()))&&s.getHost()!=null&&s.getHost().equals(u.getHost())&&s.getPort()==u.getPort();}
 void connect(){EditText input=new EditText(this);input.setSingleLine(true);input.setInputType(17);input.setText(getPreferences(0).getString("server","http://175.209.184.228:8765/"));AlertDialog dialog=new AlertDialog.Builder(this).setTitle("NEON STRIKE 서버 접속").setMessage("PC 서버 주소를 입력하세요. 휴대폰에서는 127.0.0.1을 사용하지 마세요.").setView(input).setPositiveButton("접속",null).setNegativeButton("종료",(d,w)->finish()).create();dialog.setOnShowListener(d->dialog.getButton(-1).setOnClickListener(v->{String value=input.getText().toString().trim();if(!value.contains("://"))value="http://"+value;Uri u=Uri.parse(value);if(u.getHost()==null||!("http".equals(u.getScheme())||"https".equals(u.getScheme()))||u.getUserInfo()!=null){input.setError("올바른 서버 주소를 입력하세요.");return;}Uri.Builder b=u.buildUpon().path("/").clearQuery().fragment(null);if(u.getPort()<0&&"http".equals(u.getScheme()))b.encodedAuthority(u.getHost()+":8765");server=b.build().toString();getPreferences(0).edit().putString("server",server).apply();web.loadUrl(server);dialog.dismiss();}));dialog.show();}
 public void onBackPressed(){web.evaluateJavascript("if(typeof playing!=='undefined'&&playing){if(typeof solo!=='undefined'&&solo)openSoloPointerMenu();else openSurrender();}",null);new AlertDialog.Builder(this).setTitle("게임 종료").setMessage("게임을 종료하시겠습니까?").setPositiveButton("종료",(d,w)->{web.evaluateJavascript("if(typeof leaveCurrentRoom==='function')leaveCurrentRoom();if(typeof removePresence==='function')removePresence();",r->finish());}).setNegativeButton("계속 플레이",null).show();}
 void enterFullscreen(){
  if(Build.VERSION.SDK_INT>=30){getWindow().setDecorFitsSystemWindows(false);WindowInsetsController c=getWindow().getInsetsController();if(c!=null){c.hide(WindowInsets.Type.systemBars());c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);}}
  else getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_LAYOUT_STABLE|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION);
 }
 public void onWindowFocusChanged(boolean focused){super.onWindowFocusChanged(focused);if(focused)enterFullscreen();}
 protected void onResume(){super.onResume();enterFullscreen();}
 protected void onDestroy(){web.destroy();super.onDestroy();}
}
