package com.neonstrike.game;
import android.app.*;import android.content.*;import android.os.*;import java.net.*;import java.io.*;import java.util.concurrent.*;import org.json.JSONObject;
public class SessionService extends Service {
 volatile String origin="",playerId="",room="";ScheduledExecutorService executor;PowerManager.WakeLock wake;
 public void onCreate(){super.onCreate();NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);nm.createNotificationChannel(new NotificationChannel("match","경기 연결",NotificationManager.IMPORTANCE_LOW));Intent open=new Intent(this,MainActivity.class);open.setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP|Intent.FLAG_ACTIVITY_CLEAR_TOP);PendingIntent pi=PendingIntent.getActivity(this,0,open,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);startForeground(8765,new Notification.Builder(this,"match").setSmallIcon(android.R.drawable.ic_media_play).setContentTitle("Neon Strike 경기 연결 유지").setContentText("돌아가서 계속 플레이할 수 있습니다.").setContentIntent(pi).setOngoing(true).build());wake=((PowerManager)getSystemService(POWER_SERVICE)).newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"NeonStrike:session");wake.acquire(26*60*1000L);executor=Executors.newSingleThreadScheduledExecutor();executor.scheduleWithFixedDelay(()->ping(),0,2,TimeUnit.SECONDS);}
 public int onStartCommand(Intent i,int flags,int startId){if(i!=null){origin=i.getStringExtra("origin");playerId=i.getStringExtra("id");room=i.getStringExtra("room");}return START_NOT_STICKY;}
 void ping(){if(origin==null||origin.length()==0)return;HttpURLConnection c=null;try{JSONObject body=new JSONObject();body.put("id",playerId);body.put("room",room);c=(HttpURLConnection)new URL(origin+"/api/session").openConnection();c.setRequestMethod("POST");c.setConnectTimeout(3000);c.setReadTimeout(3000);c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");byte[] data=body.toString().getBytes("UTF-8");c.setFixedLengthStreamingMode(data.length);try(OutputStream out=c.getOutputStream()){out.write(data);}if(c.getResponseCode()==200){ByteArrayOutputStream bytes=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))>=0)bytes.write(b,0,n);}JSONObject m=new JSONObject(bytes.toString("UTF-8")).optJSONObject("match");if(m!=null&&"ended".equals(m.optString("stage")))stopSelf();}}catch(Exception ignored){}finally{if(c!=null)c.disconnect();}}
 public IBinder onBind(Intent i){return null;}
 public void onTaskRemoved(Intent i){stopSelf();}
 public void onTimeout(int startId,int type){stopSelf();}
 public void onDestroy(){if(executor!=null)executor.shutdownNow();if(wake!=null&&wake.isHeld())wake.release();super.onDestroy();}
}
