imgsz: 640
epochs: 100
patience: 10
batch: 16
nbs: 64
workers: 4
cache: false
amp: true
device: 0
optimizer: AdamW
warmup_bias_lr: 0.0
warmup_epochs: 1.0
weight_decay: 0.0005
lrf: 0.2
cos_lr: true
close_mosaic: 0
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
flipud: 0.0
fliplr: 0.5
seed: 73
plots: false
save: true
verbose: false
freeze: 10
lr0: 3.0e-05
mosaic: 0.0
hsv_h: 0.005
hsv_s: 0.15
hsv_v: 0.15
degrees: 3.0
translate: 0.03
scale: 0.1
