imgsz: 640
epochs: 100
patience: 10
batch: 8
nbs: 64
workers: 4
cache: false
amp: true
device: 0
optimizer: AdamW
lr0: 0.0003
lrf: 0.1
warmup_epochs: 3.0
warmup_bias_lr: 0.0
weight_decay: 0.0005
cos_lr: true
mosaic: 0.2
close_mosaic: 10
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
hsv_h: 0.01
hsv_s: 0.25
hsv_v: 0.2
degrees: 5.0
translate: 0.05
scale: 0.15
fliplr: 0.5
flipud: 0.0
seed: 73
plots: false
save: true
verbose: false
