hsv_h: 0.01
hsv_s: 0.35
hsv_v: 0.3
degrees: 15.0
translate: 0.08
scale: 0.25
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.5
close_mosaic: 5
mixup: 0.0
cutmix: 0.0
copy_paste: 0.0
rect: false
imgsz: 640
batch: 16
workers: 4
cache: false
amp: true
optimizer: AdamW
lr0: 0.0001
lrf: 0.1
weight_decay: 0.0005
warmup_epochs: 1.0
epochs: 100
patience: 10
cos_lr: true
seed: 73
resume: false
device: 0
freeze: null
